language: python
python:
        - "3.5"
        - "3.6"
        - "3.7-dev"
script:
        - python tests.py
notifications:
        email:
                on_success: never
                on_failure: always
